apiVersion: v1
kind: Service
metadata:
  name: shade2-service
  namespace: shade2
spec:
  selector:
    app: shade2
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30710